# Generated by Django 6.0.6 on 2026-06-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
    ]
