# Generated by Django 6.0.6 on 2026-06-15 15:25

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_inventory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=colorfield.fields.ColorField(default='#316813', image_field=None, max_length=25, samples=None),
        ),
    ]
