# Generated by Django 6.0.6 on 2026-06-16 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_tag_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppinglisttag',
            old_name='list_item_id',
            new_name='list_item',
        ),
        migrations.AlterField(
            model_name='inventory',
            name='item_price',
            field=models.FloatField(),
        ),
    ]
