# Generated by Django 6.0.6 on 2026-06-16 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_list_item_id_shoppinglisttag_list_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglisttag',
            name='list_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='myapp.shoppinglist'),
        ),
    ]
