# Generated by Django 6.0.6 on 2026-06-17 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_shoppinglisttag_list_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='requires_id',
        ),
    ]
