# Generated by Django 6.0.6 on 2026-06-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_inventory_user_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='item_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
